### ISSUE TITLE
Unsupported Colours

### ISSUE THREAD

**Issue by valoeghese** [Plugily-Projects/TheBridge#30]
I need a team with block colour orange for a server I'm a dev on, however, I've noticed that's not supported.
Some missing colours could easily be supported:

https://github.com/Plugily-Projects/TheBridge/blob/3e8817bf4045da026b07735103e259363df21bfb/src/main/java/plugily/projects/thebridge/arena/base/Base.java#L87-L103

Orange could be represented by ChatColor.GOLD
Cyan could be ChatColor.DARK_AQUA
etc

**Comment by valoeghese** [comment]
The reason I say Cyan could be ChatColor.DARK_AQUA is because Cyan teracotta is quite dark

**Comment by Tigerpanzer02** [comment]
gold is now orange, and cyan dark aqua ;)
