### ISSUE TITLE
How we recompile this ?

### ISSUE THREAD

**Issue by adrien-pw** [Plugily-Projects/TheBridge#32]
Hello,

Sorry for posting this issue but, I search everywere without any answer.
Once we have downloaded the source zip file, how to recompile this with Eclipse ?

I have the plugin.yml error.

**Comment by Tigerpanzer02** [comment]
I am not sure what you mean by I have the plugin.yml error but you won't be able to build the plugin without maven.

**Comment by adrien-pw** [comment]
> I am not sure what you mean by I have the plugin.yml error but you won't be able to build the plugin without maven.

I can build the plugin but I have an error with plugin.yml who not exists…

**Comment by Tigerpanzer02** [comment]
still it exists on resource folder, look through your files.

**Comment by adrien-pw** [comment]
> still it exists on resource folder, look through your files.

Yes of course in the src/resources but when I start the server with my build, they show me an error who say that the plugin.yml not exist..

**Comment by Tigerpanzer02** [comment]
as I said its a issue how you build the plugin, its recommend to use maven only. If you just want to get the plugin you can get it on our discord server as its not recommend for not advanced users to build it on their own
