### ISSUE TITLE
Bulk Feature Request

### ISSUE THREAD

**Issue by LolFin2022** [Plugily-Projects/TheBridge#34]
Lobby 
--------------------------------------------------------------------------------------------------------------------------------
1. Lobby Protection
2. Lobby Item
3. Lobby Score-Board
4. Better Lobby Chat Formatting
---------------------------------------------------------------------------------------------------------------------------------
Please Work on These new features because World Edit and World Guard's latest version only supports 1.13-1.18
_____________________________________________________________________________________________________________________________
World Restore System
----------------------------------------------------------------------------------------------------------------------------------
1. The World Restore system doesn't work for unbreakable block.(Implement a method of the world being saved as a separate file instead of being removed without reloading)....[Can be achievable with the use of Slime World Manager API]
2. Make it so that the plugin spawns the cage instead of it removing the cage(Using Schematics)
_____________________________________________________________________________________________________________________________
Cosmetics
----------------------------------------------------------------------------------------------------------------------------------
This can maybe implemented by using other cosmetic plugins like MinigamesAddon

**Comment by Tigerpanzer02** [comment]
Thanks for opening this request. We are handling feedback and ideas through feedbacky so please write your ideas there. https://app.feedbacky.net/b/TheBridge
Furthermore make sure that you ideas have an direct impact on thebridge and not a request about a gerneral plugin which helps you in managing your lobby. You can tell us your plugin ideas on our discord. https://discord.plugily.xyz
Feel free to contact us on our discord ;)
