### ISSUE TITLE
RESET_BLOCKS not working after the first time

### ISSUE THREAD

**Issue by mikechenczy** [Plugily-Projects/TheBridge#70]
RESET_BLOCKS not working after the first time.
getArenaOption("RESET_BLOCKS") return 0 after a game.
The error is generated from plugily.projects.thebridge.arena.managers.MapRestorerManager.fullyRestoreArena()
That calls "this.arena.loadArenaOptions();", which just loads basic options, no special options for TheBridge.
The code's problem is that the special options are only set when arena is first registered, rather than set in the loading methods like loadArenaOptions().

The simplest way to solve it is the following code in Arena.java

```
@Override
  public void loadArenaOptions() {
    int BASE_PLAYER_SIZE;
    int MODE_VALUE;
    int RESET_BLOCKS;
    int RESET_TIME;
    try {
      BASE_PLAYER_SIZE = getArenaOption("BASE_PLAYER_SIZE");
      MODE_VALUE = getArenaOption("MODE_VALUE");
      RESET_BLOCKS = getArenaOption("RESET_BLOCKS");
      RESET_TIME = getArenaOption("RESET_TIME");
    } catch (Exception ignored) {
      super.loadArenaOptions();
      return;
    }
    super.loadArenaOptions();
    setArenaOption("BASE_PLAYER_SIZE", BASE_PLAYER_SIZE);
    setArenaOption("MODE_VALUE", MODE_VALUE);
    setArenaOption("RESET_BLOCKS", RESET_BLOCKS);
    setArenaOption("RESET_TIME", RESET_TIME);
  }
```

However, this isn't a good solution. It generates potential bugs for future functions. Code reconstructing is necessary for the next version to fix this.

**Comment by Tigerpanzer02** [comment]
Thanks for your report, it got fixed with https://github.com/Plugily-Projects/TheBridge/commit/83b193b7fd8f16720589a322a1722ae1906a49b3
